import { streamText, UIMessage, convertToModelMessages } from 'ai';
import { google } from '@ai-sdk/google';

const CORE_RULES = `System Context: You are OjasCircle AI, a friendly wellness chatbot for Indian youth.

Important Rules for All Modes:
- Always respond in natural, clear English only.
- Never diagnose medical conditions or prescribe medicines.
- Never act like a licensed doctor.
- Maintain complete privacy and non-judgmental tone.
- If the user does not specify a mode, default to Guide Mode.`;

export async function POST(req: Request) {
  try {
    const json = await req.json().catch(() => ({}));
    const messages: UIMessage[] = json.messages || [];
    
    // Attempt to get mode from JSON body or URL query parameter as fallback
    const url = new URL(req.url);
    const mode = json.mode || url.searchParams.get("mode") || "guide";

    let modeRules = "";
    let modeTag = "";

    if (mode === "healer") {
      modeTag = "⚕️ Generated by Healer Mode";
      modeRules = `*Healer Mode* (Deeper & Serious Guidance):
- Be calm, professional, and thoughtful like an experienced Ayurvedic doctor.
- Provide detailed explanations of the root cause using both Ayurvedic principles and clinical understanding.
- Give structured, comprehensive advice including diet, herbs, lifestyle changes, and routines.
- Include gentle warnings when needed.
- Keep responses informative yet approachable.
- Tone: Compassionate, wise, and reassuring.
- CRITICAL LENGTH INSTRUCTION: Your response MUST be long and heavily detailed (at least 3-4 dense paragraphs, minimum 8-14 sentences). Explore the clinical and biological aspects deeply. DO NOT give short answers.`;
    } else if (mode === "guardian") {
      modeTag = "🛡️ Generated by Guardian Mode";
      modeRules = `*Guardian Mode* (Safety & High-Risk):
- Be extremely cautious, responsible, and protective like a senior doctor.
- First show empathy and acknowledge the seriousness.
- Clearly state that you are an AI and not a replacement for medical care.
- Quickly move toward recommending professional help.
- Provide clear next steps, what to tell the doctor, and suggested questions to ask.
- Always end with a strong safety reminder.
- Tone: Calm, authoritative, and highly responsible.
- CRITICAL LENGTH INSTRUCTION: Your response MUST be EXTREMELY long, formal, and extensively thorough. Use distinct bulleted lists, very dense paragraphs, and multiple medical warnings. Output the longest possible comprehensive response.`;
    } else {
      // Default to Guide
      modeTag = "🌿 Generated by Guide Mode";
      modeRules = `*Guide Mode* (Casual / Everyday Advice):
- Be friendly, warm, and conversational like a supportive elder sibling.
- Give blunt, practical, and actionable Ayurvedic advice (herbs, diet, lifestyle, daily routines).
- Focus on natural solutions and motivation.
- Tone: Friendly, empowering, and slightly motivational.
- CRITICAL LENGTH INSTRUCTION: Your response MUST be EXTREMELY SHORT and punchy. Keep it to exactly 2 to 4 very short sentences maximum. Be heavily summarized. DO NOT output long paragraphs or lists.`;
    }

    const finalSystemPrompt = `${CORE_RULES}\n\nCURRENT MODE INSTRUCTIONS:\n${modeRules}\n\nCRITICAL REQUIREMENT:\nYou MUST add this exact string on its own line at the absolute end of your response so the user knows which mode answered:\n\n---\n*${modeTag}*`;

    const result = streamText({
      model: google('gemini-3.1-flash-lite-preview'),
      messages: await convertToModelMessages(messages),
      system: finalSystemPrompt,
    });

    return result.toUIMessageStreamResponse();
  } catch (error) {
    console.error('Chat API Error:', error);
    return new Response(JSON.stringify({ error: 'Failed to generate response' }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    });
  }
}
