"use client";

import { Bot, Sparkles } from "lucide-react";
import { motion } from "framer-motion";

export interface Message {
  id: string;
  role: "user" | "assistant";
  content: string;
}

// Extracts the mode tag (e.g. "🌿 Generated by Guide Mode") from the end of an AI message
function parseModeTag(text: string): { cleanText: string; tag: string | null } {
  const tagPattern = /\n---\n\*([^*]+)\*\s*$/;
  const match = text.match(tagPattern);
  if (match) {
    return {
      cleanText: text.replace(tagPattern, "").trimEnd(),
      tag: match[1].trim(),
    };
  }
  return { cleanText: text, tag: null };
}

function getModeStyle(tag: string) {
  if (tag.includes("Healer"))  return { bg: "bg-blue-950/70",   border: "border-blue-500/50",   text: "text-blue-300"   };
  if (tag.includes("Guardian"))return { bg: "bg-purple-950/70", border: "border-purple-500/50", text: "text-purple-300" };
  return                               { bg: "bg-emerald-950/70",border: "border-emerald-500/50",text: "text-emerald-300"};
}

const renderFormattedText = (text: string) => {
  return text.split("\n").map((line, i) => {
    if (!line.trim()) return <div key={i} className="h-2" />;

    const isBullet = line.trim().match(/^[-*•]\s+(.*)/);
    const isNumber = line.trim().match(/^(\d+)\.\s+(.*)/);
    const isHeader = line.trim().match(/^\*\*([^*]+)\*\*\s*:?\s*$/);

    const formatBold = (str: string) => {
      const parts = str.split(/(\*\*.*?\*\*)/g);
      return parts.map((part, j) =>
        part.startsWith("**") && part.endsWith("**")
          ? <strong key={j} className="text-white font-semibold">{part.slice(2, -2)}</strong>
          : part
      );
    };

    if (isHeader) {
      return <p key={i} className="text-white font-bold text-sm mt-3 mb-1">{isHeader[1]}</p>;
    }
    if (isBullet) {
      return (
        <div key={i} className="flex gap-3 mt-1.5 mb-1.5">
          <span className="text-silver mt-1 shrink-0"><Sparkles size={13} /></span>
          <span className="text-white/80 leading-relaxed font-light">{formatBold(isBullet[1])}</span>
        </div>
      );
    }
    if (isNumber) {
      return (
        <div key={i} className="flex gap-3 mt-1.5 mb-1.5">
          <span className="text-pure-white font-bold shrink-0">{isNumber[1]}.</span>
          <span className="text-white/80 leading-relaxed font-light">{formatBold(isNumber[2])}</span>
        </div>
      );
    }
    return <p key={i} className="mb-2 text-white/80 leading-relaxed font-light">{formatBold(line)}</p>;
  });
};

interface ChatMessageProps {
  msg: Message;
}

export function ChatMessage({ msg }: ChatMessageProps) {
  let displayText = msg.content;
  let modeTag: string | null = null;

  if (msg.role === "assistant") {
    const parsed = parseModeTag(msg.content);
    displayText = parsed.cleanText;
    modeTag = parsed.tag;
  }

  const modeStyle = modeTag ? getModeStyle(modeTag) : null;

  return (
    <motion.div
      initial={{ opacity: 0, y: 10, scale: 0.98 }}
      animate={{ opacity: 1, y: 0, scale: 1 }}
      className={`flex gap-4 sm:gap-6 w-full ${msg.role === "user" ? "justify-end" : "justify-start"}`}
    >
      {msg.role === "assistant" && (
        <div className="shrink-0 w-8 h-8 rounded-full bg-pure-white/20 flex items-center justify-center mt-1 border border-pure-white/30 shadow-[0_0_15px_rgba(108,122,224,0.2)]">
          <Bot size={16} className="text-pure-white" />
        </div>
      )}

      <div className={`max-w-[85%] md:max-w-[75%] ${
        msg.role === "user"
          ? "px-6 py-4 rounded-3xl rounded-tr-md bg-linear-to-br from-aqua/20 to-aqua/10 text-white border border-aqua/30 shadow-[0_8px_32px_rgba(244,160,36,0.1)] backdrop-blur-md"
          : "text-white/90"
      }`}>
        {msg.role === "assistant" ? (
          <div className="prose prose-invert prose-p:leading-relaxed prose-p:font-light prose-strong:text-white max-w-none">
            {renderFormattedText(displayText)}

            {/* Mode Tag Badge — shown only when AI appends the tag */}
            {modeTag && modeStyle && (
              <div className="mt-4 pt-3 border-t border-white/10">
                <span className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-semibold border backdrop-blur-sm ${modeStyle.bg} ${modeStyle.border} ${modeStyle.text}`}>
                  {modeTag}
                </span>
              </div>
            )}
          </div>
        ) : (
          <p className="text-[15px] font-medium leading-relaxed">{msg.content}</p>
        )}
      </div>
    </motion.div>
  );
}
